categories:
- Sequence Analysis
- Transcriptomics
description: UMI-tools extract - Extract UMIs from fastq
homepage_url: https://github.com/CGATOxford/UMI-tools
long_description: |
  Extract UMI barcode from a read and add it to the read name, leaving
  any sample barcode in place. Can deal with paired end reads and UMIs
  split across the paired ends
name: umi-tools_extract
owner: iuc
type: unrestricted
auto_tool_repositories:
  name_template: "umi-tools_{{ tool_id }}"
  description_template: "Wrapper for the UMI-tools suite tool: {{ tool_name }}"
suite:
  name: "suite_umi-tools"
  description: UMI-tools - Tools for dealing with Unique Molecular Identifiers
  long_description:
    This repository contains tools for dealing with Unique Molecular Identifiers (UMIs)/Random Molecular Tags (RMTs).

    https://github.com/CGATOxford/UMI-tools