categories:
- Variant Analysis
name: gatk4_mutect2
owner: iuc
homepage_url: https://software.broadinstitute.org/gatk/gatk4
description: A Galaxy wrapper for Mutect2 from GATK
long_description: |
  GATK4 is the first and only open-source software package that covers all major
  variantclasses for both germline and cancer genome analysis. This new version
  of GATK has been completely reengineered to solve key performance bottlenecks,
  increasing speed and scalability without sacrificing its trademark accuracy.
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tool_collections/gatk4
type: unrestricted
