name: vsnp_build_tables
owner: iuc
description: |
  Contains a tool that produces annotated SNP tables in the form of Excel spreadsheets.
homepage_url: https://github.com/USDA-VS/vSNP
long_description: |
  Contains a tool that accepts a combination of single SNPs json, average MQ json and newick files
  (or associated collections of each) to produce annotated SNPs tables in the form of Excel spreadsheets.
  The SNPs json and average MQ json files are typically produced by the vsnp_get_snps tool and the newick
  files are typically produced by the raxml tool.
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/vsnp_build_tables
type: unrestricted
categories:
  - Sequence Analysis
