categories: 
    -Sequence Analysis
description: Analysis of positional mismatches
long_description: A tool to count and visualize the distribution of positional mismatches on reads of High throughput DNA sequencing experiments
name: tasmanian_mismatch
owner: iuc
remote_repository_url: https://github.com/nebiolabs/tasmanian-mismatch
