categories:
- Sequence Analysis
description: 'SAVAGE: Strain Aware VirAl GEnome assembly'
long_description: 'SAVAGE is a computational tool for reconstructing individual
  haplotypes of intra-host virus strains (a viral quasispecies) without the need
  for a high quality reference genome. SAVAGE makes use of either FM-index based
  data structures or ad-hoc consensus reference sequence for constructing
  overlap graphs from patient sample data. In this overlap graph, nodes
  represent reads and/or contigs, while edges reflect that two reads/contigs,
  based on sound statistical considerations, represent identical haplotypic
  sequence. Following an iterative scheme, a new overlap assembly algorithm that
  is based on the enumeration of statistically well-calibrated groups of
  reads/contigs then efficiently reconstructs the individual haplotypes from
  this overlap graph.'
name: savage
owner: iuc
homepage_url: https://bitbucket.org/jbaaijens/savage/src/master/
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/savage
type: unrestricted

