categories: [Phylogenetics]
description: Accurate inference of orthologous gene groups made easy
long_description: OrthoFinder is a fast, accurate and comprehensive analysis tool
  for comparative genomics. It finds orthologues and orthogroups infers gene trees
  for all orthogroups and infers a rooted species tree for the species being analysed.
  OrthoFinder also provides comprehensive statistics for comparative genomic analyses
name: orthofinder
owner: iuc
remote_repository_url: =https://github.com/davidemms/OrthoFinder
