categories:
- Web Services
description: EBI Search is a scalable text search engine that provides easy and uniform access to the biological data resources hosted at the European Bioinformatics Institute (EMBL-EBI)
homepage_url: http://www.ebi.ac.uk/ebisearch/
long_description: |
    EBI Search, also named as 'EB-eye', is a scalable search engine that:

    - provides text search functionality and uniform access to resources and services hosted at the European Bioinformatics Institute (EMBL-EBI)
    - is based on the consolidated  Apache Lucene  technology
    - exposes both a Web and  RESTful Web Services interfaces
    - provides inter-domain navigation via a network of cross-references

    Here, sample clients provided by EBI is used
name: ebi_search
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/ebi_search
type: unrestricted