categories:
- Graphics
description: Build Circos Plots in Galaxy
long_description: |
    Allows for creation of circos plots from a Galaxy tool, offering the
    ability to create novel circos plots depending on the needs of the
    researcher and their workflow.
name: circos
owner: eric-rasche
remote_repository_url: https://github.com/TAMU-CPT/galaxy-circos-tool
type: unrestricted
