sudo: false
language: python
python: 2.7

before_install:
  - export GALAXY_REPO=https://github.com/galaxyproject/galaxy
  - export GALAXY_RELEASE=release_17.01
  - export PLANEMO_CONDA_PREFIX="$HOME/conda"

install:
  - pip install flake8 flake8-import-order planemo==0.39
  - planemo conda_init --conda_prefix "$PLANEMO_CONDA_PREFIX"
  - export PATH="$PLANEMO_CONDA_PREFIX/bin:$PATH"
  - conda create -y -q -c bioconda --name iuc_conda samtools=0.1.19 bcftools
  - . activate iuc_conda
  - planemo --version
  - conda --version

script:
  - set -e
  - cd "$TRAVIS_BUILD_DIR" && flake8 --ignore=E501,I201,I100 -v --exclude=.git .
  - planemo shed_lint --tools --ensure_metadata --urls --report_level warn --fail_level error --recursive .
  - planemo conda_install --conda_prefix "$PLANEMO_CONDA_PREFIX" .
  - planemo test --conda_dependency_resolution --galaxy_branch $GALAXY_RELEASE --galaxy_source $GALAXY_REPO .
  - planemo test --conda_dependency_resolution --conda_prefix "$PLANEMO_CONDA_PREFIX" --galaxy_branch "$GALAXY_RELEASE" --galaxy_source "$GALAXY_REPO" .
