categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  0.9.8 of Geo Pertea's GffCompare package.
long_description: |
  GffCompare is a modified version of the cufflinks suite's CuffCompare.

  https://github.com/gpertea/gffcompare/blob/v0.9.8/README.md
  http://cole-trapnell-lab.github.io/cufflinks/cuffcompare/
name: package_gffcompare_0_9_8
owner: iuc
homepage_url: https://github.com/gpertea/gffcompare/
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/packages/package_gffcompare_0_9_8
type: tool_dependency_definition
