categories:
- Sequence Analysis
description: Secondary structure and accessibility predictor from the Rost Lab
long_description: |
    Reprof is a protein secondary structure and accessibility predictor from
    the Rost Lab. Prediction is either done from protein sequence alone or from
    an alignment - the latter should be used for optimal performance.

    https://github.com/Rostlab/reprof/
name: reprof
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/reprof
type: unrestricted
