categories:
- SAM
description: merge multiple sorted alignment files
long_description: |
  Merge multiple sorted alignment files, producing a single sorted output file that contains all the input records and maintains the existing sort order.
name: samtools_merge
owner: devteam
homepage_url: http://www.htslib.org/
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tool_collections/samtools/samtools_merge
type: unrestricted
