categories:
  - Text Manipulation
description: tsv file to loompy file converter
long_description: |
  Creates hd5 loom files from tsv inputs
owner: iuc
name: tsv_to_loompy
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/loompy_convert
type: unrestricted
