categories:
- Data Managers
description: Data Manager for building STAR indexes
long_description: |
  STAR is an ultrafast universal RNA-seq aligner.
  WARNING! Indexing will consume mucm  RAM (9*size of fasta file, 30G 
  for human).
name: data_manager_star_index_builder
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/data_managers/data_manager_star_index_builder
type: unrestricted
