categories:
- Annotation
description: Performs GO Enrichment analysis.
homepage_url: https://github.com/DanFaria/GOEnrichment
long_description: |
  GOEnrichment is a tool for performing GO Enrichment Analysis of a set of gene products. 
  It incorporates a graph summarization method to simplify the output.
  It also contains another tool (GOSlimmer) to transform GO Annotations to slimmed versions of GO.
name: goenrichment
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/goenrichment
type: unrestricted
