
categories: [Transcriptomics]
description: Barcode contamination discovery tool
long_description: |
  This tool provides plots outlining the discovery of cross-contamination of samples across a full selection barcodes used in an scRNA analysis. 
name: crosscontamination_filter
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/crosscontamination_filter
