categories:
  - Metagenomics
owner: iuc
homepage_url: http://cran.r-project.org/web/packages/vegan/index.html
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/vegan/
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "{{ tool_name }} (using the Vegan R package)"
suite:
  name: "suite_vegan"
  description: Trinity tools to assemble transcript sequences from Illumina RNA-Seq data.
