name: "Single-Cell hdf5 matrix to text"
owner: iuc
description: "anndata (Annotated Data) and Loompy, converting between hdf5 files and different formats"
homepage_url: https://anndata.readthedocs.io
long_description: |
    AnnData provides a scalable way of keeping track of data together with learned annotations. It is used within Scanpy, for which it was initially developed. Loompy is a similar method of dealing with hdf5 files, containing layers of matrices with the same row and column attributes. Information on loompy is is available at: <http://loompy.org>
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/anndata/
type: unrestricted
categories:
- Transcriptomics
- Sequence Analysis
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for the anndata tool suite and loom files"
suite:
  name: "suite_hd5"
  description: "anndata (Annotated Data) and Loompy"
  long_description: |
    AnnData provides a scalable way of keeping track of data together with learned annotations. It is used within Scanpy, for which it was initially developed. Loompy is a similar method of dealing with hdf5 files, containing layers of matrices with the same row and column attributes. Information on loompy is is available at: <http://loompy.org>
