categories:
  - Sequence Analysis
  - Variant Analysis
homepage_url: https://github.com/ekg/seqwish
description: alignment to variation graph inducer
long_description: |
    These sequences wish they were squished into a graph.
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/seqwih/
type: unrestricted
