name: samtools
owner: iuc
description: Galaxy wrappers for the SAMtools package
homepage_url: http://www.htslib.org/
long_description: |
  SAM (Sequence Alignment/Map) format is a generic format for storing large
  nucleotide sequence alignments. The Samtools package of command line
  utilities lets you read, write, edit, index and view data in SAM format,
  and in the related binary formats BAM and CRAM.
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tool_collections/samtools
type: unrestricted
categories:
- SAM
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for samtools application {{ tool_name }}."
suite:
  name: "suite_samtools"
  description: "A suite of Galaxy tools designed to work with version 1.2 of the SAMtools package."
  long_description: |
    SAM (Sequence Alignment/Map) format is a generic format for storing large nucleotide sequence
    alignments.  These associated Galaxy utilities consist of a Galaxy Data
    Manager contained in the repository named data_manager_sam_fasta_index_builder and Galaxy tools
    contained in several separate repositories.
  owner: iuc
