categories:
- Web Services
- Data Source
description: Tools to query and download data from several EMBL-EBI databases
homepage_url: http://www.ebi.ac.uk/services/all
long_description: |
    The European Bioinformatics Institute (EMBL-EBI) maintains the world’s most comprehensive range of freely available and up-to-date molecular databases. 

    This tool suite combines tools to query and download data from several EMBL-EBI databases.
name: ebi_tools
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/ebi_tools
type: unrestricted