name: scater
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconductor-loomexperiment=1.0.4
  - bioconductor-scater=1.10.1
  - r-ggpubr=0.2.1
  - r-mvoutlier=2.0.9
  - r-optparse=1.6.2
  - r-rtsne=0.15
  - r-scales=1.0.0
  - r-workflowscriptscommon=0.0.4
