name: drep
owner: iuc
categories: 
- Metagenomics
description: dRep compares and dereplicates genome sets
long_description: dRep can rapidly and accurately compare 
  a list of genomes in a pair-wise manner. 
  This allows identification of groups of organisms that share 
  similar DNA content in terms of Average Nucleotide Identity (ANI).
  The default options for drep dereplicate use checkm method lineage_wf 
  that uses pplacer which can require more than 40 Gb of RAM. 

homepage_url: 'https://github.com/MrOlm/drep'
remote_repository_url: 'https://github.com/galaxyproject/tools-iuc/tree/master/tools/drep'
type: unrestricted
