name: drep
owner: jjohnson
categories: 
- Metagenomics
description: dRep compares and dereplicates genome sets
long_description: dRep can rapidly and accurately compare 
  a list of genomes in a pair-wise manner. 
  This allows identification of groups of organisms that share 
  similar DNA content in terms of Average Nucleotide Identity (ANI).

homepage_url: 'https://github.com/MrOlm/drep'
remote_repository_url: 'https://github.com/galaxyproteomics/tools-galaxyp/tree/master/tools/drep'
type: unrestricted
