categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and extract version
  2.2.0 of the FANN library.
long_description: |
    Fast Artificial Neural Network (FANN) Library is a free open source neural
    network library, which implements multilayer artificial neural networks in
    C with support for both fully connected and sparsely connected networks.

    Cross-platform execution in both fixed and floating point are supported. It
    includes a framework for easy handling of training data sets. It is easy to
    use, versatile, well documented, and fast.

    Bindings to more than 15 programming languages are available.

    An easy to read introduction article and a reference manual accompanies the
    library with examples and recommendations on how to use the library.

    Several graphical user interfaces are also available for the library.

    https://github.com/libfann/fann
name: package_fann_2_2_0
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/packages/package_fann_2_2_0
homepage_url: http://leenissen.dk/fann/wp/
type: tool_dependency_definition
