categories:
    - Visualization
    - Variant Analysis
homepage_url: https://CRAN.R-project.org/package=qqman
auto_tool_repositories:
    name_template: "{{ tool_id }}"
    description_template: "Manattan plot tool from the qqman package"
suite:
    name: suite_qq
    description: "Tools from the qq package"
    type: repository_suite_definition
owner: iuc
remote_repository_url: https://CRAN.R-project.org/package=qqman
long_description: The qqman package enables the flexible creation of manhattan plots, both genome-wide and for single chromosomes, with optional highlighting of SNPs of interest.
type: unrestricted