categories:
- Transcriptomics
- RNA
- Statistics
description: This tool implements the Ensemble of Gene Set Enrichment Analyses (EGSEA) method for gene set testing
homepage_url: https://bioconductor.org/packages/release/bioc/html/EGSEA.html
long_description: |
  The EGSEA package implements the Ensemble of Gene Set Enrichment Analysis
  (EGSEA) algorithm that utilizes the analysis results of twelve prominent Gene Set Enrichment 
  algorithms in the literature to calculate collective significance scores for each gene set. 
name: egsea
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/egsea
type: unrestricted
