name: iqtree
owner: iuc
description: Efficient phylogenomic software by maximum likelihood
homepage_url: http://www.iqtree.org/
remote_repository_url: https://github.com/mtekman/tools-iuc/tree/iqtree-dev
categories:
  - Phylogenetics
