name: iqtree
owner: iuc
description: Efficient phylogenomic software by maximum likelihood
homepage_url: http://www.iqtree.org/
remote_repository_url: https://testtoolshed.g2.bx.psu.edu/view/mtekman/iqtree/
categories:
  - Phylogenetics
