categories:
- Text Manipulation
homepage_url: https://cran.r-project.org/web/packages/reshape2/index.html
long_description: 
Flexibly restructure and aggregate data using just the two functions melt and 'dcast' (or 'acast').

  License: MIT 
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "{{ tool_name }} tool from the datamash package"
suite:
  name: reshape2
  description: Functions of reshape2 to melt and cast data
  type: repository_suite_definition
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/reshape2
type: unrestricted