categories:
  - Text Manipulation
homepage_url: https://cran.r-project.org/web/packages/reshape2/index.html
long_description: |
  Flexibly restructure and aggregate data using just the two functions melt and dcast
owner: iuc
name: reshape2
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/reshape2
type: unrestricted
