name: mykrobe
owner: iuc
description: Antibiotic resistance predictions
long_description: Rapid antibiotic-resistance predictions from genome sequence data for Staphylococcus aureus and Mycobacterium tuberculosis
categories:
  - Sequence Analysis
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/mykrobe
homepage_url: https://github.com/iqbal-lab/Mykrobe-predictor