categories:
- Transcriptomics
description: 'Chimeric Read Annotator for RNA-RNA interactome data'
homepage_url: https://github.com/pavanvidem/chira
long_description: |
  ChiRA is a set of tools to analyze RNA-RNA interactome experimental data such as CLASH, CLEAR-CLIP, PARIS, LIGR-Seq etc. Following are the descriptions of the each tool. Here we provide descriptions about the input and ouptput files. For the detailed description of the other parameters please look at the help texts of tools.
name: ChiRA
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/chira
type: unrestricted
