categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and extract version
  1.0.1 of the reprof package.
long_description: |
    Reprof is a protein secondary structure and accessibility predictor from
    the Rost Lab. Prediction is either done from protein sequence alone or from
    an alignment - the latter should be used for optimal performance. The
    algorithm's implementation first started in Mar 24, 2011 and the language
    choosen was Perl.

    https://github.com/Rostlab/reprof
name: package_reprof_1_0_1
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/packages/package_reprof_1_0_1
type: tool_dependency_definition
