categories:
- Sequence Analysis
homepage_url: https://github.com/nboley/idr
long_description: |
    The IDR (Irreproducible Discovery Rate) framework is a uniﬁed approach to measure
    the reproducibility of ﬁndings identiﬁed from replicate experiments and provide
    highly stable thresholds based on reproducibility. Unlike the usual scalar measures
    of reproducibility, the IDR approach creates a curve, which quantitatively assesses
    when the ﬁndings are no longer consistent across replicates.
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/idr/
type: unrestricted
name: idr
description: Galaxy wrappers for the IDR package from Nathan Boleu
