name: scoary
owner: iuc
description: Scoary calculates the assocations between all genes in the accessory genome and the traits.
homepage_url: https://github.com/BrooksLabUCSC/flair
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/scoary
type: unrestricted
categories:
    - Metagenomic Analyis
