categories: [Phylogenetics]
description: Detects positive selection
long_description: codeml is from the paml package which gathers tools for phylogenetic
  analysis by maximum likelyhood
name: codeml
owner: iuc
