categories:
- Transcriptomics
description: Quantify abundances of RNA-Seq transcripts
homepage_url: https://pachterlab.github.io/kallisto/
long_description: |
    kallisto is a program for quantifying abundances of transcripts from RNA-Seq
    data, or more generally of target sequences using high-throughput sequencing
    reads. It is based on the novel idea of pseudoalignment for rapidly 
    determining the compatibility of reads with targets, without the need for 
    alignment.
name: kallisto_quant
owner: iuc
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/kallisto_quant/
type: unrestricted
