categories:
- Amino Acids
- Sequence Analysis
- Gene Annotation
name: kofamscan
owner: iuc
description: Gene function annotation tool based on KEGG Orthology and hidden Markov model
homepage_url: https://github.com/takaram/kofam_scan
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/kofamscan
type: unrestricted