name: ucsc_fasplit
owner: iuc
description: fasplit is a tool to split single fasta file to multiple fasta files
homepage_url: http://hgdownload.cse.ucsc.edu/admin/exe/
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/ucsc-tools/fasplit
type: unrestricted
categories:
  - Fasta Manipulation
