categories:
- Assembly
- Fastq Manipulation
description: Multiple Sequence Alignment Bootstrapping Tool
homepage_url: https://github.com/phac-nml/msaboot
long_description: This tool can be used to generate bootstrapped replicates of multiple sequence alignments.
name: msaboot
owner: phac-nml
remote_repository_url: https://github.com/phac-nml/msaboot
type: unrestricted
