categories:
- Assembly
description: Automatically optimize Velvet assemblies
long_description: |
   Automatically optimizes the k-mer size and coverage cutoff of Velvet assemblies based on default or user selectable optimisation functions.
name: velvetoptimiser
owner: iuc
type: unrestricted
