name: hivclustering
owner: veg
description: Make inferences on HIV transmission networks
remote_repository_url: https://github.com/galaxyproject/tools-iuc/tree/master/tools/hivclustering/
homepage_url: https://github.com/veg/hivclustering/
type: unrestricted
categories:
 - Next Gen Mappers
