name: tbprofiler 
owner: iuc
description: Processes M. tuberculosis sequence data to infer strain type and identify known drug resistance markers. 
homepage_url: https://github.com/jodyphelan/TBProfiler
long_description: |
  This repository contains a complete rewrite of the web version of TBProfiler, described here.
  It allows the use of profiling through a command line interface and contains some additional
  functionality such as the ability to process minION data.

  The pipeline aligns reads to the H37Rv reference using bowtie2, BWA or minimap2
  and then calls variants using SAMtools. These variants are then compared to a
  drug-resistance database. We also predict the number of reads supporting drug
  resistance variants as an insight into hetero-resistance (not applicable for minION data)
  
  Full documentation at https://github.com/jodyphelan/TBProfiler 
remote_repository_url: https://github.com/galaxyproject/tools-iuc/blob/master/tools/tb-profiler
type: unrestricted
categories:
  - Sequence Analysis

repositories:
  tb_profiler_profile:
    description: "Predict M. tuberculosis lineage and drug resistance from sequences in FASTQ or BAM"
    include:
      - tb_profiler_profile.xml
  tb_profiler_vcf_profile:
    description: "Predict M. tuberculosis lineage and drug resistance from variants in VCF"
    include:
      - tb_profiler_vcf_profile.xml

suite:
  name: "suite_tbprofiler"
  description: Processes M. tuberculosis sequence data to infer strain type and identify known drug resistance markers. 
  long_description: |
    This repository contains a complete rewrite of the web version of TBProfiler, described here.
    It allows the use of profiling through a command line interface and contains some additional
    functionality such as the ability to process minION data.
  
    The pipeline aligns reads to the H37Rv reference using bowtie2, BWA or minimap2
    and then calls variants using SAMtools. These variants are then compared to a
    drug-resistance database. We also predict the number of reads supporting drug
    resistance variants as an insight into hetero-resistance (not applicable for minION data)
    
    Full documentation at https://github.com/jodyphelan/TBProfiler 
